server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/App_Fitness_Ai
      database: App_Fitness_Ai

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: ai-fitness.exchange
  queue:
    name: ai-activity.queue
  routing:
    key: ai-activity.tracking