server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/user/preferences/**
        - id: training-card-service
          uri: lb://TRAINING-CARD-SERVICE
          predicates:
            - Path=/api/user/card/**

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: QzU2eXpQbW56N2JDUHlWRmtHbWhnQTRmZWR6YmhrVjE=
  expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

